config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from variant.views import index_view

urlpatterns = [
]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', index_view, name='home'),
    path('account/', include('user.urls')),
    path('test/', include('variant.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from user.forms import CustomAuthenticationForm
from user.views import RegisterView, DetailProfileView, logout_view, EditProfileView, DeleteProfileView

app_name = 'account'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path(
        'login/',
        LoginView.as_view(authentication_form=CustomAuthenticationForm, template_name='pages/login_page.html'),
        name='login'
    ),
    path('logout/', logout_view, name='logout'),
    path('profile/detail/<int:pk>/', DetailProfileView.as_view(), name='profile_detail'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='profile_edit'),
    path('profile/delete/<int:pk>/', DeleteProfileView.as_view(), name='profile_delete'),
]

variant/urls.py
from django.contrib import admin
from django.urls import path

from variant.views import subject_list_view, subject_view, variant_view, result_view, VariantCreateView

app_name = 'test'
urlpatterns = [
    path('subjects/', subject_list_view, name='subject_list'),
    path('subjects/<int:pk>/', subject_view, name='subject'),
    path('variant/<int:pk>/', variant_view, name='variant'),
    path('variant/edit/<int:pk>/', variant_view, name='variant_edit'),
    path('variant/delete/<int:pk>/', variant_view, name='variant_delete'),
    path('results/<int:pk>/', result_view, name='result'),

    # for teachers
    path('variant/create/', VariantCreateView.as_view(), name='variant_create'),
]

templates/pages/delete_profile_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Delete Profile
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <form method="post">
                    {% csrf_token %}
                    <h4 class="mb-4">
                        {% blocktrans %}{{ object }} - akkountingizni rostdan o'chirmoqchimisiz?{% endblocktrans %}
                    </h4>
                    {{ form }}
                    <input type="submit" value="{% blocktranslate %}Tasdiqlash{% endblocktranslate %}">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/edit_profile_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Edit Profile
{% endblock %}

{% block content %}

    <div class="container mt-4">
        <div class="row">
            <div class="col">
                <h3>{% blocktrans %}Profil ma'lumotlarini o'zgartirish{% endblocktrans %}</h3>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">
                        {% blocktrans %}Saqlash{% endblocktrans %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/exercise_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Variant: {{ variant.title }}
{% endblock %}

{% block content %}
    <div class="container mt-4">

        <h4>{{ variant.subject }} <i class="bi bi-chevron-right"></i> {{ variant.title }}</h4>
        <form method="post" class="mt-4">
            {% csrf_token %}
            <ol class="list-group">
                {% for exercise in exercise_list %}
                    <li class="list-group-item d-flex flex-column">
                        <h6>{{ forloop.counter }}. {{ exercise.text }}</h6>

                        <div class="form-check">
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_a"
                                   value="answer_a" class="form-check-input"
                                   data-exercise="{{ exercise.id }}">
                            <label class="form-check-label"
                                   for="{{ exercise.id }}_answer_a">A) {{ exercise.answer_a }}</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_b"
                                   value="answer_b" class="form-check-input"
                                   data-exercise="{{ exercise.id }}">
                            <label class="form-check-label"
                                   for="{{ exercise.id }}_answer_b">B) {{ exercise.answer_b }}</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_c"
                                   value="answer_c" class="form-check-input"
                                   data-exercise="{{ exercise.id }}">
                            <label class="form-check-label"
                                   for="{{ exercise.id }}_answer_c">C) {{ exercise.answer_c }}</label>
                        </div>
                        <div class="form-check">
                            <input type="radio" name="{{ exercise.id }}" id="{{ exercise.id }}_answer_d"
                                   value="answer_d" class="form-check-input"
                                   data-exercise="{{ exercise.id }}">
                            <label class="form-check-label"
                                   for="{{ exercise.id }}_answer_d">D) {{ exercise.answer_d }}</label>
                        </div>
                    </li>
                {% endfor %}
            </ol>
            <button type="submit" class="btn btn-primary mt-3">
                {% blocktrans %}Tekshirish{% endblocktrans %}
            </button>
        </form>


    </div>
{% endblock %}

templates/pages/home_page.html
{% extends 'base.html' %}

{% block title %}
    Home page
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Welcome to Home page!</h1>
    </div>
{% endblock %}

templates/pages/login_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="post" class="auth-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-3 w-100">
                {% blocktrans %}Kirish{% endblocktrans %}
            </button>
        </form>

    </div>
{% endblock %}

templates/pages/profile_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Profile
{% endblock %}

{% block content %}

    <div class="container mt-4">
        <div class="row">

            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{ user.avatar.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">
                            {% blocktrans %}Foydalanuvchi ma'lumotlari{% endblocktrans %}
                        </h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        {% if user.username != '' %}
                            <li class="list-group-item">
                                <b>{% blocktrans %}Foydalanuvchi nomi:{% endblocktrans %}</b>
                                <i>{{ user.username }}</i>
                            </li>
                        {% endif %}
                        {% if user.email != '' %}
                            <li class="list-group-item">
                                <b>Email:</b>
                                <i>{{ user.email }}</i>
                            </li>
                        {% endif %}
                        {% if user.last_name != '' %}
                            <li class="list-group-item">
                                <b>{% blocktrans %}Ism:{% endblocktrans %}</b>
                                <i>{{ user.first_name }}</i>
                            </li>
                        {% endif %}
                        {% if user.last_name != '' %}
                            <li class="list-group-item">
                                <b>{% blocktrans %}Familiya:{% endblocktrans %}</b>
                                <i>{{ user.last_name }}</i>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="card-body">
                        <a href="{% url 'account:profile_edit' request.user.pk %}" class="card-link">
                            {% blocktrans %}O'zgartirish{% endblocktrans %}
                        </a>
                        <a href="{% url 'account:profile_delete' request.user.pk %}" class="card-link">
                            {% blocktrans %}O'chirish{% endblocktrans %}
                        </a>
                    </div>
                </div>
            </div>

            <div class="col-9">
                <h4 class="mb-4">{% blocktrans %}Testlar natijalari:{% endblocktrans %}</h4>
                {% if result_list %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">№</th>
                            <th scope="col">{% blocktrans %}Variant{% endblocktrans %}</th>
                            <th scope="col">{% blocktrans %}Ko'rsatkich{% endblocktrans %}</th>
                            <th scope="col">{% blocktrans %}To'g'ri javoblar{% endblocktrans %}</th>
                            <th scope="col">{% blocktrans %}Noto'g'ri javoblar{% endblocktrans %}</th>
                            <th scope="col">{% blocktrans %}Ishlangan vaqti{% endblocktrans %}</th>
                        </tr>
                        </thead>
                        <tbody class="table-group-divider">
                        {% for result in result_list %}

                            <tr class="{% if result.signpost > 90 %}
                                    table-success
                                    {% elif result.signpost < 60 %}
                                    table-danger
                            {% endif %} ">
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>
                                    <a href="{% url 'test:result' result.result.id %}"
                                       class="d-flex w-100 justify-content-between">
                                        {{ result.result }}
                                    </a>
                                </td>
                                <td>{{ result.signpost }}%</td>
                                <td>{{ result.count_correct }}</td>
                                <td>{{ result.count_incorrect }}</td>
                                <td>{{ result.result.date_completed|date:"d/m/Y H:i:s" }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h3>{% blocktrans %}Sizda ishlangan variantlar mavjud emas!{% endblocktrans %}</h3>
                {% endif %}
            </div>
        </div>

    </div>
{% endblock %}

templates/pages/register_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Register
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <form method="post" class="auth-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary mt-3 w-100">
                {% blocktrans %}Yuborish{% endblocktrans %}
            </button>
        </form>
    </div>

{% endblock %}

templates/pages/result_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Natija
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h3>{% blocktrans %}Natijangiz{% endblocktrans %}: {{ ball }} / {{ count }}</h3>

        <ol class="list-group mt-4">
            {% for result in object_list %}
                <li class="list-group-item d-flex flex-column">
                    <h6>{{ forloop.counter }}. {{ result.exercise.text }}</h6>
                    <div>
                        A) {{ result.exercise.answer_a }}
                        <span style="color: {% if result.user_answer == 'answer_a' %}
                            {% if result.exercise.answer == 'answer_a' %} #50ce38 {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_a' %}
                                {% if result.exercise.answer == 'answer_a' %} ✓ {% else %} ✕ {% endif %}
                            {% endif %}
                        </span>
                    </div>

                    <div>
                        B) {{ result.exercise.answer_b }}
                        <span style="color: {% if result.user_answer == 'answer_b' %}
                            {% if result.exercise.answer == 'answer_b' %} #50ce38 {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_b' %}
                                {% if result.exercise.answer == 'answer_b' %} ✓ {% else %} ✕ {% endif %}
                            {% endif %}
                        </span>
                    </div>

                    <div>
                        C) {{ result.exercise.answer_c }}
                        <span style="color: {% if result.user_answer == 'answer_c' %}
                            {% if result.exercise.answer == 'answer_c' %} #50ce38 {% else %} red {% endif %}
                        {% endif %}">
                            {% if result.user_answer == 'answer_c' %}
                                {% if result.exercise.answer == 'answer_c' %} ✓ {% else %} ✕ {% endif %}
                            {% endif %}
                        </span>
                    </div>

                    <div>
                        D) {{ result.exercise.answer_d }}
                        <span style="color: {% if result.user_answer == 'answer_d' %}
                            {% if result.exercise.answer == 'answer_d' %} #50ce38 {% else %} red {% endif %}
                            {% endif %}">
                            {% if result.user_answer == 'answer_d' %}
                                {% if result.exercise.answer == 'answer_d' %} ✓ {% else %} ✕ {% endif %}
                            {% endif %}
                        </span>
                    </div>
                </li>
            {% endfor %}
        </ol>
    </div>

{% endblock %}

templates/pages/subject_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Fanlar
{% endblock %}


{% block content %}
    <div class="container mt-4">
        <h4>{% blocktrans %}Fanni tanlang:{% endblocktrans %}</h4>
        <div class="list-group">
            {% for subject in subject_list %}
                <a href="{% url 'test:subject' subject.id %}"
                   class="list-group-item list-group-item-action">{{ subject.name }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/variant_create.html
{% extends 'base.html' %}
{% load static widget_tweaks %}

{% block title %}
    Variant yaratish
{% endblock %}


{% block content %}

    <div class="container py-5">
        <h1>Variant yaratish:</h1>
{#        <form method="get">#}
{#            <select name="lang" id="lang" hx-get="/">#}
{#                <option value="uz">uz</option>#}
{#                <option value="ru">ru</option>#}
{#                <option value="en">en</option>#}
{#            </select>#}
{#        </form>#}
        <form method="post">
            {% csrf_token %}

            {% for field in variant_form %}
                <div class="fieldWrapper mt-3">
                    {{ field|add_label_class:"form-label" }}
                    {{ field|add_class:"form-control" }}
                </div>
            {% endfor %}

            <hr>

            <div class="row">
                {% for form in formset %}
                    <div class="col-4 shadow p-3 mb-5 bg-body-tertiary rounded">
                        {% for field in form %}
                            {% if field.name not in "id, variant" %}
                                {{ field|add_label_class:"form-label mt-3" }}
                                {{ field|add_class:"form-control"|attr:"rows:3" }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            <button type="submit" class="btn btn-outline-success mt-4">Saqlash</button>
        </form>
    </div>
{% endblock %}

templates/pages/variant_edit.html
{% extends 'base.html' %}

{% block title %}
    Variantni o'zgartirish
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <ul>
                    {% for exercise in exercise_list %}
                        <li>{{ exercise }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/variant_page.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    Variant
{% endblock %}


{% block content %}

    <div class="container mt-4">

        {% if request.user.is_staff %}
            <a href="{% url 'test:variant_create' %}?subject={{ subject.id|urlencode }}">Variant yaratish</a>
        {% endif %}

        <h4 class="mt-4">{% blocktrans %}Variantni tanlang:{% endblocktrans %}</h4>
        <div class="list-group">
            {% for variant in variant_list %}
                <a href="{% url 'test:variant' variant.id %}"
                   class="list-group-item list-group-item-action">{{ variant.title }}</a>
            {% endfor %}
        </div>
    </div>

{% endblock %}